server:
  port: 8080

spring:
  application:
    name: Tech Pulse

  datasource:
    url: jdbc:postgresql://dpg-d4k5vmndiees73bahfm0-a.singapore-postgres.render.com:5432/pro_techpulse_fck5
    username: techpulse
    password: 08Vz2gEWeKdWu44SV8nZoQgAr76hIS4z

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # options: none, validate, update, create, create-drop

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
